### ISSUE TITLE
So, I got this message earlier today.

### ISSUE THREAD

**Issue by nahid-hridoy** [project-mmxix/happyaddons-issues#1]
Howdy!

Since WordPress 5.2 there is a built-in feature that detects when a plugin or theme causes a fatal error on your site, and notifies you with this automated email.

In this case, WordPress caught an error with one of your plugins, Happy Elementor Addons.

First, visit your website (https://nahidmahamud.com/nmh47/) and check for any visible issues. Next, visit the page where the error was caught (https://nahidmahamud.com/nmh47/nmh47/wp-admin/post.php?post=4259&action=elementor) and check for any visible issues.

Please contact your host for assistance with investigating this issue further.

If your site appears broken and you can't access your dashboard normally, WordPress now has a special "recovery mode". This lets you safely login to your dashboard and investigate further.

https://nahidmahamud.com/nmh47/wp-login.php?action=enter_recovery_mode&rm_token=BPIVY7bzNcxSD0Z6X0HWci&rm_key=v9GDRl4C9Hxo29NA1FyBiL

To keep your site safe, this link will expire in 1 day. Don't worry about that, though: a new link will be emailed to you if the error occurs again after it expires.

Error Details
=============
An error of type E_ERROR was caused in line 650 of the file /home/nahifavo/public_html/nmh47/wp-content/plugins/happy-elementor-addons/widgets/icon-box/widget.php. Error message: Uncaught Error: Call to undefined method Happy_Addons\Elementor\Widget\Icon_Box::render_edit_tools() in /home/nahifavo/public_html/nmh47/wp-content/plugins/happy-elementor-addons/widgets/icon-box/widget.php:650
Stack trace:
#0 /home/nahifavo/public_html/nmh47/wp-content/plugins/elementor/includes/base/widget-base.php(561): Happy_Addons\Elementor\Widget\Icon_Box->render_content()
#1 /home/nahifavo/public_html/nmh47/wp-content/plugins/elementor/includes/base/element-base.php(622): Elementor\Widget_Base->get_raw_data(true)
#2 /home/nahifavo/public_html/nmh47/wp-content/plugins/elementor/includes/base/element-base.php(622): Elementor\Element_Base->get_raw_data(true)
#3 /home/nahifavo/public_html/nmh47/wp-content/plugins/elementor/includes/base/element-base.php(622): Elementor\Element_Base->get_raw_data(true)
#4 /home/nahifavo/public_html/nmh47/wp-content/plugins/elementor/includes/base/element-base.php(622): Elementor\Element_Base->get_raw_data(true)
#5 /home/nahifavo/public_html/nmh47/wp-content/plugins/elemento

**Comment by hasinhayder** [comment]
We're looking into this issue and we will update you as soon as possible. Thanks for reporting this issue

**Comment by hasinhayder** [comment]
This issue has been fixed. Please update the plugin to the latest version. If you still see this issue, let me know please.
