### ISSUE TITLE
Website bug on image compare (twentytwenty is not a function)

### ISSUE THREAD

**Issue by AustinGil** [project-mmxix/happyaddons-issues#2]
I'm not sure if this is a bug with the plugin or just the website, but the twentytwenty JS plugin used for the image compare is not defined (https://happyaddons.com/elementor-image-compare-widget-demo/#) resulting in `Uncaught TypeError: t.twentytwenty is not a function`

**Comment by hasinhayder** [comment]
We're having a look at this and we will update you as soon as possible. Thanks for reporting it

**Comment by hasinhayder** [comment]
This has been fixed, was valid for only the website and released plugin was not affected. Thanks for your time to report it brother.

**Comment by AustinGil** [comment]
Cool. Nice job on the fast fix. Glad to hear it was an isolated issue.
